name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Update Rust
      run: |
        rustup default stable
        rustup update nightly
        rustup update stable
        rustup target add wasm32-unknown-unknown --toolchain nightly

    - name: Test
      run: SKIP_WASM_BUILD=1 cargo test --release
   
    - name: Check Build
      run: SKIP_WASM_BUILD=1 cargo check --release

    - name: Check Build for Benchmarking
      run: cargo check --features=runtime-benchmarks --release
